### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Shadow59i** [panshak/accountill#18]
Hello,

I have a problem when starting the Client part.

When I do "npm start" I get this error.

> Starting the development server...
> 
> Error: error:0308010C:digital envelope routines::unsupported
>     at new Hash (node:internal/crypto/hash:67:19)
>     at Object.createHash (node:crypto:133:10)
>     at module.exports (C:\Users\AdrienLcq\Downloads\accountill-0.1.3\client\node_modules\webpack\lib\util\createHash.js:135:53)
>     at NormalModule._initBuildHash (C:\Users\AdrienLcq\Downloads\accountill-> 0.1.3\client\node_modules\webpack\lib\NormalModule.js:417:16)
>     at handleParseError (C:\Users\AdrienLcq\Downloads\accountill-0.1.3\client\node_modules\webpack\lib\NormalModule.js:471:10)
>     at C:\Users\AdrienLcq\Downloads\accountill-0.1.3\client\node_modules\webpack\lib\NormalModule.js:er.js:233:18
>     at context.callback (C:\Users\AdrienLcq\Downloads\accountill-0.1.3\client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
>     at C:\Users\AdrienLcq\Downloads\accountill-0.1.3\client\node_modules\babel-loader\lib\index.js:59:103 {
>   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],  library: 'digital envelope routines',
>   reason: 'unsupported',  code: 'ERR_OSSL_EVP_UNSUPPORTED'
> }
> 
> Node.js v18.3.0

Thank you for your help

**Comment by raphael-as** [comment]
how to fix ?
